name: test workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubantu-lastest
    steps:
      - uses: actions/checkout@v2 
      - name: hello world
        run: echo "hello world"
        shell: bash
  goodbye:
    runs-on: ubantu-lastest
    steps:
      - name: good bye
        run: echo "it is the end"
        shell: bash
      
    
    
  
    


